In [160]:
# Importing the 'os' module, which provides functions to interact with the operating system
import os

# Printing the absolute path of the current working directory.
# This can be useful for understanding where your files are being saved or loaded from.
print(os.path.abspath('.'))

C:\Users\Administrator\Python_Data Analytics & Maching Learning


In [161]:
# Importing the NumPy library, which is essential for performing numerical operations in Python.
# NumPy provides support for large, multi-dimensional arrays and matrices, as well as high-level
# mathematical functions to operate on these arrays. 
# 'np' is a common alias used to refer to NumPy.
import numpy as np

In [7]:
# Creating a simple Python list of integers
array = [1, 2, 3, 4, 5]

# Attempting to add 1 to the list directly, which will raise a TypeError.
# Lists do not support element-wise addition. 
# You cannot add a scalar (like 1) to a list directly; Python expects another list for concatenation.
# To perform element-wise addition, we need a NumPy array (shown in the next cells).
array + 1


TypeError: can only concatenate list (not "int") to list

In [162]:
# Creating a NumPy array from a Python list. NumPy arrays allow element-wise operations.
# NumPy arrays are more powerful than Python lists because they support vectorized operations,
# which means you can perform mathematical operations on the whole array without loops.
array = np.array([1, 2, 3, 4, 5])

# Printing the type of the object to confirm it's a NumPy array (numpy.ndarray).
print(type(array))

<class 'numpy.ndarray'>


In [9]:
# Adding 1 to each element of the NumPy array using element-wise addition.
# This is possible because NumPy supports broadcasting, which allows operations
# to be automatically applied across all elements of the array.
array2 = array + 1

# Displaying the result. The output will be a new array with 1 added to each element.
array2

array([2, 3, 4, 5, 6])

In [10]:
array2 + array

array([ 3,  5,  7,  9, 11])

In [11]:
array2 * array

array([ 2,  6, 12, 20, 30])

In [12]:
array.shape

(5,)

In [13]:
# Lists in Python do not have the 'shape' attribute because they are not NumPy arrays.
# This will raise an AttributeError since 'shape' is only available for NumPy arrays.
tang_list = [1, 2, 3, 4, 5]
tang_list.shape  # This will result in an AttributeError.

AttributeError: 'list' object has no attribute 'shape'

In [15]:
# Creating a 2D NumPy array (matrix) with two rows and three columns.
# The inner lists [1,2,3] and [4,5,6] represent the rows of the array.
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
tang_list = [1,2,3,4,5]
tang_array = np.array(tang_list)
tang_array

array([1, 2, 3, 4, 5])

In [18]:
# Creating a list with mixed types: integers and a string '5'.
tang_list = [1, 2, 3, 4, '5']

# Converting the list into a NumPy array.
# Since NumPy arrays must have uniform data types, the elements will all be converted to strings.
tang_array = np.array(tang_list)

# Displaying the resulting array.
tang_array

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [164]:
# Creating a list with integers and a float 5.0.
tang_list = [1, 2, 3, 4, 5.0]

# Converting the list into a NumPy array.
# Since NumPy arrays require uniform data types, all integers will be cast to floats.
tang_array = np.array(tang_list)

In [165]:
# 'tang_array.size' returns the total number of elements in the array.
# For example, if the array is 1D with 5 elements, 'size' will return 5.
tang_array.size

5

In [166]:
# 'tang_array.ndim' returns the number of dimensions of the array.
# A 1D array will return 1, a 2D array (like a matrix) will return 2, and so on.
tang_array.ndim

1

In [24]:
tang_array[1:3]

array([2., 3.])

In [25]:
tang_array[-2:]

array([4., 5.])

In [27]:
# Creating a 2D NumPy array (matrix) with three rows and three columns.
# The array contains three rows: [1, 2, 3], [4, 5, 6], and [7, 8, 9].
tang_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Modifying the element at row index 1 and column index 1 (the value '5') and changing it to 10.
tang_array[1, 1] = 10

tang_array

array([[ 1,  2,  3],
       [ 4, 10,  6],
       [ 7,  8,  9]])

In [29]:
# Accessing and displaying the entire second row of the array.
# In this case, 'tang_array[1]' returns the second row: [4, 10, 6].
tang_array[1]

array([ 4, 10,  6])

In [30]:
# Accessing and displaying the entire second column of the array (index 1).
# The syntax 'tang_array[:, 1]' uses the colon ':' to select all rows and '1' to select the second column.
tang_array[:, 1]

array([ 2, 10,  8])

In [32]:
# Creating a 1D NumPy array with values ranging from 0 to 100, with a step of 10.
# 'np.arange(0, 100, 10)' generates values starting from 0, ending before 100, with a step size of 10.
tang_array = np.arange(0, 100, 10)

# Displaying the array: it will contain [0, 10, 20, 30, 40, 50, 60, 70, 80, 90].
tang_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
# Creating a boolean mask using an array of 0's and 1's.
# 0's will be interpreted as False, and 1's will be interpreted as True.
# This mask allows selecting specific elements from 'tang_array'.
mask = np.array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1], dtype=bool)

mask

array([False, False, False,  True,  True,  True, False, False,  True,
        True])

In [35]:
# Using the mask to select elements where the mask is True.
# This will return the elements from 'tang_array' where the mask has True values.
tang_array[mask]

array([30, 40, 50, 80, 90])

In [37]:
# Creating a random array of 10 values between 0 and 1 using 'np.random.rand'.
# The array contains random values uniformly distributed between 0 and 1.
random_array = np.random.rand(10)
random_array

array([0.82267662, 0.19156392, 0.3952473 , 0.81042629, 0.51338277,
       0.37494213, 0.52019718, 0.69867526, 0.50075107, 0.4363915 ])

In [38]:
# Creating a boolean mask where the condition 'random_array > 0.5' is True.
# This mask will be True for values greater than 0.5, and False otherwise.
mask = random_array > 0.5
mask

array([ True, False, False,  True,  True, False,  True,  True,  True,
       False])

In [39]:
# Creating a new 1D array with values [10, 20, 30, 40, 50].
tang_array = np.array([10, 20, 30, 40, 50])

# 'np.where' returns the indices of elements in 'tang_array' that satisfy the condition.
# In this case, it returns the indices of elements greater than 30.
np.where(tang_array > 30)

(array([3, 4], dtype=int64),)

In [40]:
# Using 'np.where' to directly select elements from 'tang_array' that are greater than 30.
# This returns the values themselves rather than their indices.
tang_array[np.where(tang_array > 30)]

array([40, 50])

In [41]:
# Creating two NumPy arrays 'x' and 'y'.
y = np.array([1, 1, 1, 4])
x = np.array([1, 1, 1, 2])

# Performing an element-wise comparison between 'x' and 'y'.
# This returns a boolean array where 'True' means the elements at the same position in 'x' and 'y' are equal, and 'False' otherwise.
x == y

array([ True,  True,  True, False])

In [42]:
# Performing an element-wise logical AND between 'x' and 'y'.
# 'np.logical_and' returns True where both 'x' and 'y' have non-zero values at the same position.
np.logical_and(x, y)

array([ True,  True,  True,  True])

In [43]:
# Performing an element-wise logical OR between 'x' and 'y'.
# 'np.logical_or' returns True if at least one of the values in 'x' or 'y' at the same index is non-zero.
np.logical_or(x, y)

array([ True,  True,  True,  True])

In [45]:
# Creating a NumPy array with floating-point numbers and explicitly specifying the data type as float32.
tang_array = np.array([1, 2, 3, 4, 5], dtype=np.float32)
tang_array

array([1., 2., 3., 4., 5.], dtype=float32)

In [46]:
# Checking the data type of the array.
tang_array.dtype

dtype('float32')

In [48]:
# Creating a NumPy array with mixed data types (strings and numbers) and specifying the data type as object.
tang_array = np.array(['1', '10', '3.5', 'str'], dtype=object)

tang_array

array(['1', '10', '3.5', 'str'], dtype=object)

In [50]:
# Creating a NumPy array with integers.
tang_array = np.array([1, 2, 3, 4, 5])

# Creating a new array by converting 'tang_array' to float32 using 'np.asarray'.
tang_array2 = np.asarray(tang_array, dtype=np.float32)

tang_array2

array([1., 2., 3., 4., 5.], dtype=float32)

In [54]:
# Creating a 2D array (matrix).
tang_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Assigning 'tang_array' to 'tang_array2'. Both arrays now point to the same memory location.
tang_array2 = tang_array

tang_array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
# Modifying an element in 'tang_array2'. Since both arrays point to the same data, 'tang_array' will also reflect this change.
tang_array2[1, 1] = 100

print(tang_array2,'\n')
print(tang_array)

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]] 

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [65]:
# Creating a deep copy of 'tang_array' using 'copy()'.
# This creates a new array in a different memory location, so changes to 'tang_array2' will not affect 'tang_array'.
tang_array2 = tang_array.copy()

# Modifying an element in 'tang_array2'. This will not affect the original 'tang_array'.
tang_array2[1, 1] = 10000

print(tang_array2,'\n')
print(tang_array)

[[    1     2     3]
 [    4 10000     6]
 [    7     8     9]] 

[[  1   2   3]
 [  4 100   6]
 [  7   8   9]]


In [66]:
# Calculating the sum of all elements in 'tang_array2'.
np.sum(tang_array2)

10040

In [69]:
# Summing the elements of 'tang_array' along the columns (axis 0).
np.sum(tang_array, axis=0)

array([ 12, 110,  18])

In [70]:
# Summing the elements of 'tang_array' along the rows (axis 1).
np.sum(tang_array, axis=1)

array([  6, 110,  24])

In [71]:
# Calculating the product of all elements in 'tang_array'.
tang_array.prod()

7257600

In [72]:
# Calculating the product of elements along the columns (axis 0).
tang_array.prod(axis=0)

array([  28, 1600,  162])

In [73]:
# Calculating the product of elements along the rows (axis 1).
tang_array.prod(axis=1)

array([   6, 2400,  504])

In [75]:
# Finding the minimum value in the entire array.
tang_array.min()

1

In [76]:
# Finding the minimum value along the columns (axis 0).
tang_array.min(axis=0)

array([1, 2, 3])

In [77]:
tang_array.min(axis = 1)

array([1, 4, 7])

In [78]:
# Calculating the mean (average) of all elements in 'tang_array'.
tang_array.mean()

15.555555555555555

In [79]:
# Calculating the mean of elements along the rows (axis=1).
# This returns the average value for each row.
tang_array.mean(axis=1)

array([ 2.        , 36.66666667,  8.        ])

In [80]:
# Calculating the standard deviation of all elements in 'tang_array'.
tang_array.std()

29.96706010535609

In [81]:
# Calculating the standard deviation along the rows (axis=1).
# This returns the standard deviation for each row.
tang_array.std(axis=1)

array([ 0.81649658, 44.79087209,  0.81649658])

In [82]:
# Calculating the variance of all elements in 'tang_array'.
tang_array.var()

898.0246913580246

In [83]:
# Clipping the values in 'tang_array' to the range [2, 4].
# Any values less than 2 will be set to 2, and any values greater than 4 will be set to 4.
tang_array.clip(2, 4)

array([[2, 2, 3],
       [4, 4, 4],
       [4, 4, 4]])

In [88]:
# Creating a NumPy array with floating-point values.
q_array = np.array([1.23, 2.35, 3.46, 4.57, 5.62, 6.73, 7.81, 8.92])

# Rounding all elements in 'q_array' to the nearest integer.
q_array.round()

array([1., 2., 3., 5., 6., 7., 8., 9.])

In [89]:
# Rounding all elements in 'q_array' to one decimal place.
q_array.round(decimals=1)

array([1.2, 2.4, 3.5, 4.6, 5.6, 6.7, 7.8, 8.9])

In [90]:
# Finding the index of the minimum element in 'q_array'.
q_array.argmin()

0

In [92]:
# Finding the index of the minimum element along each column (axis=0) in 'tang_array2'.
tang_array2.argmin(axis=0)

array([0, 0, 0], dtype=int64)

In [93]:
# Finding the index of the minimum element along each row (axis=1) in 'tang_array2'.
tang_array2.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [94]:
# Creating two NumPy arrays 'x' and 'y'.
x = np.array([5, 5])
y = np.array([2, 2])

# Performing element-wise multiplication of 'x' and 'y'.
np.multiply(x, y)

array([10, 10])

In [95]:
# Performing the dot product of 'x' and 'y'.
np.dot(x, y)


20

In [97]:
# Reshaping 'x' to a 2x1 column vector.
x.shape = 2, 1
x

array([[5],
       [5]])

In [98]:
# Performing the dot product between the reshaped 'x' and 'y'.
np.dot(x, y)

ValueError: shapes (2,1) and (2,) not aligned: 1 (dim 1) != 2 (dim 0)

In [100]:
# Reshaping 'y' to a 1x2 row vector.
y.shape = 1, 2
y

array([[2, 2]])

In [102]:
# Creating two 2D arrays 'a' and 'b'.
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenating 'a' and 'b' along the default axis (axis=0, vertically).
# This stacks 'b' below 'a', resulting in a larger 2D array.
np.concatenate((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [103]:
# Concatenating 'a' and 'b' along axis=1 (horizontally).
# This stacks 'b' to the right of 'a', resulting in a wider 2D array.
np.concatenate((a, b), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [104]:
# Stacking the 1D arrays 'd' and 'e' along a new axis using 'np.stack'.
d = np.array([1, 2, 3])
e = np.array([2, 3, 4])

# np.stack((d, e)) stacks the 1D arrays d and e along a new axis, creating a 2D array. 
np.stack((d, e))

array([[1, 2, 3],
       [2, 3, 4]])

In [105]:
# Horizontally stacking 'a' and 'b' using 'np.hstack', which is equivalent to concatenation along axis=1.
np.hstack((a, b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [106]:
# Vertically stacking 'a' and 'b' using 'np.vstack', which is equivalent to concatenation along axis=0.
np.vstack((a, b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [159]:
# Flattening the 2D array 'q_array' into a 1D array using 'flatten()'.
q_array = np.array([[1, 2, 3], [4, 5, 6]])
flattened_array = q_array.flatten()

# Displaying the flattened array.
flattened_array

array([1, 2, 3, 4, 5, 6])

In [113]:
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [114]:
# Creating an array of 5 values logarithmically spaced between 10^0 and 10^1.
# np.logspace(0, 1, 5) generates 5 values spaced evenly on a logarithmic scale between 10^0 and 10^1

np.logspace(0, 1, 5)

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])

In [115]:
# Creating a 1D array of integers from 0 to 4 using 'np.r_'.
np.r_[0:5:1]

array([0, 1, 2, 3, 4])

In [116]:
# Creating a column array using the 'np.c_' function.
# The slice '0:5:1' means "start at 0, stop at 5, step by 1".
# This function concatenates the values into a column vector.
# The result is a column array of values from 0 to 4.
np.c_[0:5:1]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [117]:
# Creating a one-dimensional array with 3 elements, all initialized to 0.
# The 'zeros' function is useful for initializing arrays where you plan to update values later.
np.zeros(3)

array([0., 0., 0.])

In [118]:
# Creating a 2D (3x3) array, where all elements are initialized to 0.
# The argument (3, 3) specifies the shape of the array: 3 rows and 3 columns.
# This is useful for initializing matrices for linear algebra or machine learning.
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [119]:
# Creating a 3x3 matrix filled with ones.
# Similar to 'zeros', this function can initialize arrays, but all elements are set to 1.
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [121]:
# Multiplying a 3x3 matrix of ones by 8.1.
# NumPy supports element-wise operations, so each element in the matrix is multiplied by 8.1.
# This operation demonstrates scalar multiplication on arrays.
np.ones((3, 3)) * 8.1

array([[8.1, 8.1, 8.1],
       [8.1, 8.1, 8.1],
       [8.1, 8.1, 8.1]])

In [124]:
# Creating an uninitialized array with 6 elements using 'np.empty'.
# 'empty' allocates memory but does not initialize the elements (they may contain garbage values initially).
# We then use 'fill(3)' to set each element to 3.
a = np.empty(6)
a.fill(3)  # Filling the array with the value 3.
a  # Displaying the array.

array([3., 3., 3., 3., 3., 3.])

In [125]:
# Creating a NumPy array of integers
q_array = np.array([1, 2, 3, 4])

# Creating an array with the same shape as q_array, but filled with zeros.
# 'np.zeros_like' creates a new array of zeros with the same shape and data type as the given array.
np.zeros_like(q_array)

array([0, 0, 0, 0])

In [126]:
# Creating a 5x5 identity matrix.
# 'np.identity' returns an identity matrix, which is a square matrix with ones on the diagonal and zeros elsewhere.
# Identity matrices are useful in linear algebra and matrix operations.
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [127]:
# Creating a 3x2 matrix with random values between 0 and 1.
# 'np.random.rand' generates an array of the given shape, filled with random samples from a uniform distribution over [0, 1).
np.random.rand(3, 2)

array([[0.49511113, 0.74382585],
       [0.63435761, 0.71233853],
       [0.37664926, 0.41651318]])

In [128]:
# np.random.randint(10, size=(5, 4)) generates a 5x4 array filled with random integers between 0 (inclusive) and 10 (exclusive).
np.random.randint(10, size=(5, 4))

array([[9, 2, 3, 6],
       [5, 4, 3, 1],
       [4, 3, 9, 4],
       [2, 1, 5, 5],
       [1, 1, 2, 4]])

In [129]:
# Generating a random floating-point number between 0 and 1.
np.random.rand()

0.1285439286455391

In [130]:
np.random.randint(0, 10, 3)

array([5, 3, 2])

In [157]:
# Defining the mean (mu) and standard deviation (sigma) for a normal distribution.
mu = 0
sigma = 1

# Generating an array of 10 random values from a normal distribution with mean 0 and standard deviation 1.
np.random.normal(mu, sigma, 10)

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
        0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144])

In [ ]:
# Setting the precision for printing NumPy arrays to 2 decimal places.
np.set_printoptions(precision=2)

# Generating 10 random values from a normal distribution with mean 0 and standard deviation 1, with 2 decimal places.
np.random.normal(mu, sigma, 10)

In [138]:
# Creating a NumPy array with values from 0 to 9.
q_array = np.arange(10)

# Shuffling the elements of the array in-place.
# np.random.shuffle(q_array) randomly shuffles the elements of the array q_array in-place, meaning the array is modified directly.
np.random.shuffle(q_array)

q_array

array([8, 7, 4, 2, 5, 0, 9, 1, 3, 6])

In [158]:
# Setting the random seed to ensure reproducibility of random number generation.
# np.random.seed(100) sets the seed for NumPy's random number generator. 
# This ensures that the sequence of random numbers generated will be the same every time the code is run, 
# which is useful for reproducibility.
np.random.seed(100)

# Generating 10 random values from a normal distribution with mean 0 and standard deviation 1.
np.random.normal(mu, sigma, 10)


array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
        0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144])

In [141]:
# Writing some data to a text file 'q.txt' using %%writefile magic command in Jupyter.
%%writefile q.txt
1 2 3 4 5 6
7 8 9 1 2 3

Writing q.txt


In [144]:
# Reading data from the file and processing it line by line.
data = []
with open('q.txt') as f:
    for line in f.readlines():
        fields = line.split()  # Splitting each line by spaces.
        cur_data = [float(x) for x in fields]  # Converting the values to floats.
        data.append(cur_data)
data = np.array(data)  # Converting the list to a NumPy array.
print(data)

[[1. 2. 3. 4. 5. 6.]
 [7. 8. 9. 1. 2. 3.]]


In [146]:
# Loading data directly from 'q.txt' using 'np.loadtxt', which automatically converts the data into a NumPy array.
data2 = np.loadtxt('q.txt')

print(data2)

[[1. 2. 3. 4. 5. 6.]
 [7. 8. 9. 1. 2. 3.]]


In [149]:
# Writing some comma-separated data to 'q2.txt'.
%%writefile q2.txt
1, 2, 3, 4, 5, 6
7, 8, 9, 1, 2, 3

Overwriting q2.txt


In [151]:
# # Loading the data from 'q2.txt' using a comma delimiter.
data3 = np.loadtxt('q2.txt', delimiter = ',')
print(data3)

[[1. 2. 3. 4. 5. 6.]
 [7. 8. 9. 1. 2. 3.]]


In [152]:
# Writing data with column headers to 'q2.txt'.
%%writefile q2.txt
x,y,z,w,a,b
1, 2, 3, 4, 5, 6
7, 8, 9, 1, 2, 3

Overwriting q2.txt


In [153]:
# Loading the data from 'q2.txt' and skipping the first row (which contains column headers).
data4 = np.loadtxt('q2.txt', delimiter=',', skiprows=1)
print(data4)

[[1. 2. 3. 4. 5. 6.]
 [7. 8. 9. 1. 2. 3.]]


In [154]:
# Displaying the help documentation for the 'np.loadtxt' function.
# This function is used to load data from a text file, with many configurable options.
# The help function provides detailed information about its parameters and usage.
print(help(np.loadtxt))

Help on function loadtxt in module numpy:

loadtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0, encoding='bytes', max_rows=None, *, quotechar=None, like=None)
    Load data from a text file.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must return bytes or strings. The strings
        in a list or produced by a generator are treated as lines.
    dtype : data-type, optional
        Data-type of the resulting array; default: float.  If this is a
        structured data-type, the resulting array will be 1-dimensional, and
        each row will be interpreted as an element of the array.  In this
        case, the number of columns used must match the number of fields in
        the data-type

In [155]:
# Saving a NumPy array to a text file named 'q4.txt'.
# The 'fmt' argument specifies the format of the values (in this case, integers '%d'),
# and 'delimiter' specifies that the values should be separated by commas in the file.
np.savetxt('q4.txt', q_array, fmt='%d', delimiter=',')

In [156]:
# Creating a 2x3 NumPy array.
q_array = np.array([[1, 2, 3], [4, 5, 6]])

# Saving the array to a binary file 'q5.npy'.
# The .npy format is a binary format specifically for NumPy arrays. It is more efficient
# than text formats for large datasets, preserving data types and shapes.
np.save('q5.npy', q_array)

# Loading the saved array back from the binary file.
np.load('q5.npy')

array([[1, 2, 3],
       [4, 5, 6]])